apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-backend-app
  labels:
    app: com-backend-app
spec:
  selector:
    matchLabels:
      app: com-backend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: com-backend-app
    spec:
      containers:
        - name: com-backend-app
          image: 545009863897.dkr.ecr.us-east-2.amazonaws.com/backend:latest
          ports:
            - containerPort: 8080